version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sujiakeji-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

  zuul:
    image: sujiakeji/sujiakeji-zuul
    container_name: sujiakeji-zuul
    depends_on:
      - rabbitmq
    ports:
      - 9300:9300
    environment:
      EUREKA_SERVER_HOST: sujiakeji-eureka-server
      EUREKA_SERVER_PORT: 9000
      RABBITMQ_HOST: sujiakeji-rabbitmq
      RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: dev
